name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #Should be added
          password: ${{ secrets.DOCKER_PASSWORD }} #Should be added

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bounswe/bounswe2024group8:latest  # Docker Hub kullanıcı adınız ve repository adınız

      - name: Run image
        run: |
          docker run --name myapp -d -p 80:8080 bounswe/bounswe2024group8:latest
